name: latenttsr-tsr
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - asttokens=3.0.0=py310h06a4308_0
  - attr=2.5.2=h39aace5_0
  - blas=1.0=mkl
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.16.0=ha61ee94_1012
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.1=py310h06a4308_0
  - contourpy=1.3.2=py310h3788b33_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=5.1.2=lgpl_hd27bd3a_6
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.17.0=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310h3406613_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.13.3=h4a9f257_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.41=h17648ed_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_hb72d44e_103
  - icu=70.1=h27087fc_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipykernel=6.30.1=py310h06a4308_0
  - ipython=8.30.0=py310h06a4308_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_core=5.8.1=py310h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.1.2=h409715c_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt=1.11.1=ha770c72_0
  - libgcrypt-devel=1.11.1=hb9d3cd8_0
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgcrypt-tools=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.84.4=h77a78f3_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - liblapacke=3.9.0=12_hce4cc19_netlib
  - libllvm15=15.0.7=hadd5161_1
  - libltdl=2.4.3a=h5888daf_0
  - libnghttp2=1.58.0=h47da74e_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libogg=1.3.5=hd0c01bc_1
  - libopencv=4.7.0=py310hb48cf42_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenjpeg=2.5.4=hee96239_0
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=253=h8c4010b_1
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.5.1=hffd6297_1
  - libtool=2.5.4=h5888daf_0
  - libudev1=253=h0b41bf4_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib=3.9.1=py310hff52083_1
  - matplotlib-base=3.9.1=py310hf02ac8c_2
  - matplotlib-inline=0.1.7=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py310h06a4308_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.2=py310h06a4308_0
  - nspr=4.37=h29cc59b_0
  - nss=3.117=h445c969_0
  - numpy=1.26.4=py310hb13e2d6_0
  - ocl-icd=2.3.2=h5eee18b_1
  - opencv=4.7.0=py310hff52083_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.8=h7b32b05_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_1
  - parso=0.8.4=py310h06a4308_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py310h06a4308_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py310h06a4308_0
  - ply=3.11=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=py310h06a4308_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - psutil=7.0.0=py310hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pure_eval=0.2.3=py310h06a4308_0
  - py-opencv=4.7.0=py310hfdc917e_1
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.1=py310h06a4308_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.7=py310hab646b1_3
  - pyqt5-sip=12.11.0=py310heca2aa9_3
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=27.1.0=py310hcf8288c_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.6=h602db52_6
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_0
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py310h06a4308_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py310h06a4308_0
  - statsmodels=0.14.5=py310hf779ad0_1
  - svt-av1=1.4.1=hcb278e6_0
  - sympy=1.14.0=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.3.0=pyhcf101f3_0
  - torchaudio=2.5.1=py310_cu124
  - torchtriton=3.1.0=py310
  - torchvision=0.15.2=cpu_py310h83e0c9b_0
  - tornado=6.5.2=py310h7c4b9e2_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py310h7c4b9e2_1
  - urllib3=2.5.0=py310h06a4308_0
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - git-filter-repo==2.47.0
      - imageio==2.37.0
      - lazy-loader==0.4
      - lpips==0.1.4
      - pillow==12.0.0
      - scikit-image==0.25.2
      - tifffile==2025.5.10
      - torch-fidelity==0.3.0
prefix: /data/deepesh/miniconda3/envs/latenttsr-tsr
